### INSTALLING NumPy
pip install numpy

### NumPy CODEBASE
https://github.com/numpy/numpy

### IMPORTING NumPY

In [1]:
import numpy as np

### CREATING NumPy ARRAYS

In [2]:
# From Python List
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
# 1D Array with Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# 2D Array with Ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# Array with Linspace
np.linspace(0, 20, num=10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [6]:
# Array with a Range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Array with a Range and a Step
np.arange(5, 51, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [8]:
# Array with Random Values
np.random.rand(3, 2)

array([[0.10897299, 0.57356086],
       [0.21745872, 0.49868167],
       [0.74864739, 0.57072236]])

In [9]:
# Array with Custom Values
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

### ACCESSING ELEMENTS IN ARRAYS

In [10]:
# Array
arr1 = np.array([1, 2, 3])

In [11]:
# Access the first element
arr1[0]

1

In [12]:
# Access elements from index 1 to 3
arr1[1:3]

array([2, 3])

In [13]:
# Access elements from the start to index 2
arr1[:2]

array([1, 2])

In [14]:
# Access elements from index 1 to the end
arr1[1:]

array([2, 3])

In [15]:
# Access the last element
arr1[-1]

3

### SLICING

In [16]:
# Array 
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [17]:
# Slice rows from index 1 to 2
arr2[1:3, :]

array([[4, 5, 6],
       [7, 8, 9]])

In [18]:
# Slice columns from index 0 to 1
arr2[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

### CONCATENATING

In [19]:
# Arrays
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])

In [20]:
# Concatenate
np.concatenate((a1, b1))

array([1, 2, 3, 4, 5, 6])

In [21]:
# Vertical
np.vstack((a1, b1))

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Horizontal
np.hstack((a1, b1))

array([1, 2, 3, 4, 5, 6])

### STACKING

In [23]:
# Arrays
a2 = np.array([1, 2, 3])
b2 = np.array([4, 5, 6])

In [24]:
# with axis 0
np.stack((a2, b2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# with axis 1
np.stack((a2, b2), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

### SPILITING

In [26]:
# Arrray
arr3 = np.array([1, 2, 3, 4, 5, 6])

In [27]:
np.split(arr3, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [28]:
print(np.split(arr3, [2, 4]))

[array([1, 2]), array([3, 4]), array([5, 6])]


### BROADCASTING

In [29]:
a3 = np.array([1, 2, 3])
b3 = 2

In [30]:
# Multiply 
a3 * b3

array([2, 4, 6])

In [31]:
# Plus
a3 + b3

array([3, 4, 5])

### UNIVERSAL FUNCTIONS

In [32]:
# Array 
arr4 = np.array([1, 2, 3])

In [33]:
# Sine
np.sin(arr4)

array([0.84147098, 0.90929743, 0.14112001])

In [34]:
# Cosine 
np.cos(arr4)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [35]:
# Exponential
np.exp(arr4)

array([ 2.71828183,  7.3890561 , 20.08553692])

### AGGREGATE FUNCTIONS

In [36]:
# Array 
arr5 = np.array([1, 2, 3])

In [37]:
# Minimum
arr5.min()

1

In [38]:
# Maxiumum
arr5.max()

3

In [39]:
# Varience
arr5.var()

0.6666666666666666

In [40]:
# Sum
arr5.sum()

6

In [41]:
# Mean
arr5.mean()

2.0

In [42]:
# Standard Deviation
arr5.std()

0.816496580927726

In [43]:
# Any
arr5.any()

True

In [44]:
# All
arr5.all()

True

In [45]:
# Product
arr5.prod()

6

### ARRAY MANIPULATION

In [46]:
# Transposing an Array
arr6 = np.array([[1, 2], [3, 4]])

arr6.transpose()

array([[1, 3],
       [2, 4]])

In [47]:
# Reshaping an Array
arr7 = np.array([1, 2, 3, 4])

arr7.reshape((2, 2))

array([[1, 2],
       [3, 4]])

In [48]:
# Flattening an Array
arr8 = np.array([[1, 2], [3, 4]])

arr8.flatten()

array([1, 2, 3, 4])

### ITERATING

In [49]:
arr9 = np.array([[1, 2], [3, 4]])

for x in np.nditer(arr9):
    print(x)

1
2
3
4


### MASKING

In [50]:
arr10 = np.array([1, 2, 3, 4, 5, 6])

arr10[arr10 > 3]

array([4, 5, 6])

### MESHGRID

In [51]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

X, Y = np.meshgrid(x, y)
print(X, Y)

[[1 2 3]
 [1 2 3]
 [1 2 3]] [[4 4 4]
 [5 5 5]
 [6 6 6]]
